#!/usr/bin/env python3
"""gen_assets.py -- build-time asset generator for the WhittyDemo intro.

Emits:
  demo_pic.c    -- the piece-by-piece picture (375x300, 160-colour quantized,
                   pens are 0..159; the core offsets them to 96..255)
  demo_sintab.h -- 256-entry int16 sine table, amplitude 4096
"""
import math, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
PIC_W, PIC_H, PIC_COLS = 375, 300, 160

# ---- sine table ----
with open(os.path.join(HERE, "demo_sintab.h"), "w") as f:
    f.write("/* generated by gen_assets.py -- sin(2*pi*i/256)*4096 */\n")
    f.write("static const short sintab256[256] = {\n")
    for i in range(0, 256, 8):
        row = ", ".join("%6d" % round(4096 * math.sin(2 * math.pi * j / 256))
                        for j in range(i, i + 8))
        f.write("    " + row + ",\n")
    f.write("};\n")

# ---- picture ----
src = Image.open(os.path.join(HERE, "assets", "pic_src.png")).convert("RGB")
src = src.resize((PIC_W, PIC_H), Image.LANCZOS)
q = src.quantize(colors=PIC_COLS, method=Image.MEDIANCUT, dither=Image.FLOYDSTEINBERG)
pal = q.getpalette()[:PIC_COLS * 3]
data = q.tobytes()
assert len(data) == PIC_W * PIC_H
assert max(data) < PIC_COLS

with open(os.path.join(HERE, "demo_pic.c"), "w") as f:
    f.write("/* generated by gen_assets.py from assets/pic_src.png */\n")
    f.write("const int demo_pic_w = %d;\n" % PIC_W)
    f.write("const int demo_pic_h = %d;\n" % PIC_H)
    f.write("const unsigned char demo_pic_pal[%d][3] = {\n" % PIC_COLS)
    for i in range(PIC_COLS):
        f.write("    {%3d,%3d,%3d},\n" % (pal[i*3], pal[i*3+1], pal[i*3+2]))
    f.write("};\n")
    f.write("const unsigned char demo_pic_data[%d] = {\n" % (PIC_W * PIC_H))
    for i in range(0, len(data), 24):
        f.write(",".join(str(b) for b in data[i:i+24]) + ",\n")
    f.write("};\n")

print("wrote demo_pic.c (%dx%d, %d cols) + demo_sintab.h" % (PIC_W, PIC_H, PIC_COLS))
